GET http://localhost:8080/Destinations/
Accept: application/json
Authorization: Basic aGVucmlrOmltcG9ydGFudA==

###
GET http://localhost:8080/CargoTypes/
Accept: application/json
Authorization: Basic aGVucmlrOmltcG9ydGFudA==
